# docker-compose.yml
version: "3"
services:
  postgres:
    image: postgres:11.2-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: guard
    ports: 
      - "5432:5432"